spring.application.name=ecommerce-backend

# Conexión Supabase (PostgreSQL)
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
spring.datasource.username=${DB_USERNAME:postgres.wuasopsogkicecxozyvj}
spring.datasource.password=${DB_PASSWORD:MkDmpwq6G5DBGk78}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate & JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Servidor Web
server.port=${PORT:8080}

# Habilita la carga inicial de datos y la cuenta demo.
app.data-seeder.enabled=true
